### ISSUE TITLE
Nexys 4 DDR / A7 (100T) Compatibility

### ISSUE THREAD

**Issue by shivampotdar** [enjoy-digital/litex_vexriscv_smp#3]
I read in Antmicro's blog that this design was tested with 4 cores on a 35k version of Arty A7 (and tested on 100T). Does this mean I would also be able to use the same on a Nexys A7 (formerly Nexys 4 DDR) since the FPGA model is exact same as that of A7-100T with different peripherals.
Thanks!

**Comment by enjoy-digital** [comment]
Sorry for the late anwer, this repository was an experiment and VexRiscv-SMP support is now merged in https://github.com/litex-hub/linux-on-litex-vexriscv and you board is supported. You can just configure the CPU count with --cpu-count, --cpu-count=4 should indeed also works on the Nexys A7.
